### ISSUE TITLE
Convenções para pastas e ficheiros de testes

### ISSUE THREAD

**Issue by diogohmcruz** [ltrigo/mygrant#15]
Como pomos as estruturas das pastas que contêm testes?

1. A pasta chama-se "test", "tests", "__tests__"? A convenção do Jest é "__tests__", a do Node é "tests"

2. Colocamos essa pasta na base do directório e ter uma estrutura de pastas igual ao projeto, ou em cada pasta ter uma pasta de testes?

3. Como chamar ao ficheiro de testes? Eu gosto dos ficheiros a acabar em ".test.js"

**Comment by rubenmarques-dev** [comment]
Por mim, 
1.  "tests"
2. Uma pasta tests e estrutura igual, vamos é de ter uma pasta "__mocks__" adjacente aos ficheiros "reais".
3. Prefiro ".test.js" a ".spec.js"
